export type PhoneCountry = {
  code: string;
  label: string;
  dial: string;
  length: number;
};

export const phoneCountries: PhoneCountry[] = [
  { code: "AF", label: "Afghanistan", dial: "+93", length: 9 },
  { code: "AL", label: "Albania", dial: "+355", length: 9 },
  { code: "DZ", label: "Algeria", dial: "+213", length: 9 },
  { code: "AD", label: "Andorra", dial: "+376", length: 6 },
  { code: "AO", label: "Angola", dial: "+244", length: 9 },
  { code: "AR", label: "Argentina", dial: "+54", length: 10 },
  { code: "AM", label: "Armenia", dial: "+374", length: 8 },
  { code: "AU", label: "Australia", dial: "+61", length: 9 },
  { code: "AT", label: "Austria", dial: "+43", length: 10 },
  { code: "AZ", label: "Azerbaijan", dial: "+994", length: 9 },
  { code: "BH", label: "Bahrain", dial: "+973", length: 8 },
  { code: "BD", label: "Bangladesh", dial: "+880", length: 10 },
  { code: "BY", label: "Belarus", dial: "+375", length: 9 },
  { code: "BE", label: "Belgium", dial: "+32", length: 9 },
  { code: "BZ", label: "Belize", dial: "+501", length: 7 },
  { code: "BJ", label: "Benin", dial: "+229", length: 8 },
  { code: "BT", label: "Bhutan", dial: "+975", length: 8 },
  { code: "BO", label: "Bolivia", dial: "+591", length: 8 },
  { code: "BA", label: "Bosnia and Herzegovina", dial: "+387", length: 8 },
  { code: "BW", label: "Botswana", dial: "+267", length: 8 },
  { code: "BR", label: "Brazil", dial: "+55", length: 11 },
  { code: "BN", label: "Brunei", dial: "+673", length: 7 },
  { code: "BG", label: "Bulgaria", dial: "+359", length: 9 },
  { code: "BF", label: "Burkina Faso", dial: "+226", length: 8 },
  { code: "BI", label: "Burundi", dial: "+257", length: 8 },
  { code: "KH", label: "Cambodia", dial: "+855", length: 9 },
  { code: "CM", label: "Cameroon", dial: "+237", length: 9 },
  { code: "CA", label: "Canada", dial: "+1", length: 10 },
  { code: "CF", label: "Central African Republic", dial: "+236", length: 8 },
  { code: "TD", label: "Chad", dial: "+235", length: 8 },
  { code: "CL", label: "Chile", dial: "+56", length: 9 },
  { code: "CN", label: "China", dial: "+86", length: 11 },
  { code: "CO", label: "Colombia", dial: "+57", length: 10 },
  { code: "KM", label: "Comoros", dial: "+269", length: 7 },
  { code: "CG", label: "Congo", dial: "+242", length: 9 },
  { code: "CD", label: "Congo (DRC)", dial: "+243", length: 9 },
  { code: "CR", label: "Costa Rica", dial: "+506", length: 8 },
  { code: "HR", label: "Croatia", dial: "+385", length: 9 },
  { code: "CU", label: "Cuba", dial: "+53", length: 8 },
  { code: "CY", label: "Cyprus", dial: "+357", length: 8 },
  { code: "CZ", label: "Czech Republic", dial: "+420", length: 9 },
  { code: "DK", label: "Denmark", dial: "+45", length: 8 },
  { code: "DJ", label: "Djibouti", dial: "+253", length: 8 },
  { code: "DO", label: "Dominican Republic", dial: "+1", length: 10 },
  { code: "EC", label: "Ecuador", dial: "+593", length: 9 },
  { code: "EG", label: "Egypt", dial: "+20", length: 10 },
  { code: "SV", label: "El Salvador", dial: "+503", length: 8 },
  { code: "GQ", label: "Equatorial Guinea", dial: "+240", length: 9 },
  { code: "ER", label: "Eritrea", dial: "+291", length: 7 },
  { code: "EE", label: "Estonia", dial: "+372", length: 8 },
  { code: "SZ", label: "Eswatini", dial: "+268", length: 8 },
  { code: "ET", label: "Ethiopia", dial: "+251", length: 9 },
  { code: "FJ", label: "Fiji", dial: "+679", length: 7 },
  { code: "FI", label: "Finland", dial: "+358", length: 10 },
  { code: "FR", label: "France", dial: "+33", length: 9 },
  { code: "GA", label: "Gabon", dial: "+241", length: 7 },
  { code: "GM", label: "Gambia", dial: "+220", length: 7 },
  { code: "GE", label: "Georgia", dial: "+995", length: 9 },
  { code: "DE", label: "Germany", dial: "+49", length: 10 },
  { code: "GH", label: "Ghana", dial: "+233", length: 9 },
  { code: "GR", label: "Greece", dial: "+30", length: 10 },
  { code: "GT", label: "Guatemala", dial: "+502", length: 8 },
  { code: "GN", label: "Guinea", dial: "+224", length: 9 },
  { code: "GW", label: "Guinea-Bissau", dial: "+245", length: 7 },
  { code: "GY", label: "Guyana", dial: "+592", length: 7 },
  { code: "HT", label: "Haiti", dial: "+509", length: 8 },
  { code: "HN", label: "Honduras", dial: "+504", length: 8 },
  { code: "HU", label: "Hungary", dial: "+36", length: 9 },
  { code: "IS", label: "Iceland", dial: "+354", length: 7 },
  { code: "IN", label: "India", dial: "+91", length: 10 },
  { code: "ID", label: "Indonesia", dial: "+62", length: 10 },
  { code: "IR", label: "Iran", dial: "+98", length: 10 },
  { code: "IQ", label: "Iraq", dial: "+964", length: 10 },
  { code: "IE", label: "Ireland", dial: "+353", length: 9 },
  { code: "IL", label: "Israel", dial: "+972", length: 9 },
  { code: "IT", label: "Italy", dial: "+39", length: 10 },
  { code: "JM", label: "Jamaica", dial: "+1", length: 10 },
  { code: "JP", label: "Japan", dial: "+81", length: 10 },
  { code: "JO", label: "Jordan", dial: "+962", length: 9 },
  { code: "KZ", label: "Kazakhstan", dial: "+7", length: 10 },
  { code: "KE", label: "Kenya", dial: "+254", length: 9 },
  { code: "KW", label: "Kuwait", dial: "+965", length: 8 },
  { code: "KG", label: "Kyrgyzstan", dial: "+996", length: 9 },
  { code: "LA", label: "Laos", dial: "+856", length: 9 },
  { code: "LV", label: "Latvia", dial: "+371", length: 8 },
  { code: "LB", label: "Lebanon", dial: "+961", length: 8 },
  { code: "LS", label: "Lesotho", dial: "+266", length: 8 },
  { code: "LR", label: "Liberia", dial: "+231", length: 8 },
  { code: "LY", label: "Libya", dial: "+218", length: 9 },
  { code: "LI", label: "Liechtenstein", dial: "+423", length: 7 },
  { code: "LT", label: "Lithuania", dial: "+370", length: 8 },
  { code: "LU", label: "Luxembourg", dial: "+352", length: 9 },
  { code: "MG", label: "Madagascar", dial: "+261", length: 9 },
  { code: "MW", label: "Malawi", dial: "+265", length: 9 },
  { code: "MY", label: "Malaysia", dial: "+60", length: 9 },
  { code: "MV", label: "Maldives", dial: "+960", length: 7 },
  { code: "ML", label: "Mali", dial: "+223", length: 8 },
  { code: "MT", label: "Malta", dial: "+356", length: 8 },
  { code: "MR", label: "Mauritania", dial: "+222", length: 8 },
  { code: "MU", label: "Mauritius", dial: "+230", length: 8 },
  { code: "MX", label: "Mexico", dial: "+52", length: 10 },
  { code: "MD", label: "Moldova", dial: "+373", length: 8 },
  { code: "MC", label: "Monaco", dial: "+377", length: 8 },
  { code: "MN", label: "Mongolia", dial: "+976", length: 8 },
  { code: "ME", label: "Montenegro", dial: "+382", length: 8 },
  { code: "MA", label: "Morocco", dial: "+212", length: 9 },
  { code: "MZ", label: "Mozambique", dial: "+258", length: 9 },
  { code: "MM", label: "Myanmar", dial: "+95", length: 9 },
  { code: "NA", label: "Namibia", dial: "+264", length: 9 },
  { code: "NP", label: "Nepal", dial: "+977", length: 10 },
  { code: "NL", label: "Netherlands", dial: "+31", length: 9 },
  { code: "NZ", label: "New Zealand", dial: "+64", length: 9 },
  { code: "NI", label: "Nicaragua", dial: "+505", length: 8 },
  { code: "NE", label: "Niger", dial: "+227", length: 8 },
  { code: "NG", label: "Nigeria", dial: "+234", length: 10 },
  { code: "KP", label: "North Korea", dial: "+850", length: 10 },
  { code: "MK", label: "North Macedonia", dial: "+389", length: 8 },
  { code: "NO", label: "Norway", dial: "+47", length: 8 },
  { code: "OM", label: "Oman", dial: "+968", length: 8 },
  { code: "PK", label: "Pakistan", dial: "+92", length: 11 },
  { code: "PS", label: "Palestine", dial: "+970", length: 9 },
  { code: "PA", label: "Panama", dial: "+507", length: 8 },
  { code: "PG", label: "Papua New Guinea", dial: "+675", length: 8 },
  { code: "PY", label: "Paraguay", dial: "+595", length: 9 },
  { code: "PE", label: "Peru", dial: "+51", length: 9 },
  { code: "PH", label: "Philippines", dial: "+63", length: 10 },
  { code: "PL", label: "Poland", dial: "+48", length: 9 },
  { code: "PT", label: "Portugal", dial: "+351", length: 9 },
  { code: "QA", label: "Qatar", dial: "+974", length: 8 },
  { code: "RO", label: "Romania", dial: "+40", length: 9 },
  { code: "RU", label: "Russia", dial: "+7", length: 10 },
  { code: "RW", label: "Rwanda", dial: "+250", length: 9 },
  { code: "SA", label: "Saudi Arabia", dial: "+966", length: 9 },
  { code: "SN", label: "Senegal", dial: "+221", length: 9 },
  { code: "RS", label: "Serbia", dial: "+381", length: 9 },
  { code: "SL", label: "Sierra Leone", dial: "+232", length: 8 },
  { code: "SG", label: "Singapore", dial: "+65", length: 8 },
  { code: "SK", label: "Slovakia", dial: "+421", length: 9 },
  { code: "SI", label: "Slovenia", dial: "+386", length: 8 },
  { code: "SO", label: "Somalia", dial: "+252", length: 8 },
  { code: "ZA", label: "South Africa", dial: "+27", length: 9 },
  { code: "KR", label: "South Korea", dial: "+82", length: 10 },
  { code: "SS", label: "South Sudan", dial: "+211", length: 9 },
  { code: "ES", label: "Spain", dial: "+34", length: 9 },
  { code: "LK", label: "Sri Lanka", dial: "+94", length: 9 },
  { code: "SD", label: "Sudan", dial: "+249", length: 9 },
  { code: "SE", label: "Sweden", dial: "+46", length: 9 },
  { code: "CH", label: "Switzerland", dial: "+41", length: 9 },
  { code: "SY", label: "Syria", dial: "+963", length: 9 },
  { code: "TW", label: "Taiwan", dial: "+886", length: 9 },
  { code: "TJ", label: "Tajikistan", dial: "+992", length: 9 },
  { code: "TZ", label: "Tanzania", dial: "+255", length: 9 },
  { code: "TH", label: "Thailand", dial: "+66", length: 9 },
  { code: "TL", label: "Timor-Leste", dial: "+670", length: 8 },
  { code: "TG", label: "Togo", dial: "+228", length: 8 },
  { code: "TT", label: "Trinidad and Tobago", dial: "+1", length: 10 },
  { code: "TN", label: "Tunisia", dial: "+216", length: 8 },
  { code: "TR", label: "Turkey", dial: "+90", length: 10 },
  { code: "TM", label: "Turkmenistan", dial: "+993", length: 8 },
  { code: "UG", label: "Uganda", dial: "+256", length: 9 },
  { code: "UA", label: "Ukraine", dial: "+380", length: 9 },
  { code: "AE", label: "United Arab Emirates", dial: "+971", length: 9 },
  { code: "GB", label: "United Kingdom", dial: "+44", length: 10 },
  { code: "US", label: "United States", dial: "+1", length: 10 },
  { code: "UY", label: "Uruguay", dial: "+598", length: 8 },
  { code: "UZ", label: "Uzbekistan", dial: "+998", length: 9 },
  { code: "VE", label: "Venezuela", dial: "+58", length: 10 },
  { code: "VN", label: "Vietnam", dial: "+84", length: 9 },
  { code: "YE", label: "Yemen", dial: "+967", length: 9 },
  { code: "ZM", label: "Zambia", dial: "+260", length: 9 },
  { code: "ZW", label: "Zimbabwe", dial: "+263", length: 9 }
];